-- 코드를 작성해주세요
SELECT YEAR(TB2.DIFFERENTIATION_DATE) AS YEAR, 
        MAXSIZE-TB2.SIZE_OF_COLONY AS YEAR_DEV, 
        TB2.ID
FROM 
    (SELECT DATE_FORMAT(DIFFERENTIATION_DATE, "%Y") AS YEAR, 
     MAX(SIZE_OF_COLONY) AS MAXSIZE
    FROM ECOLI_DATA
    GROUP BY DATE_FORMAT(DIFFERENTIATION_DATE, "%Y")) TB1 JOIN ECOLI_DATA TB2
ON TB1.YEAR = DATE_FORMAT(TB2.DIFFERENTIATION_DATE, "%Y")
ORDER BY YEAR, YEAR_DEV;