SELECT TB3.ID AS ID, TB4.FISH_NAME AS FISH_NAME,TB3.LENGTH AS LENGTH
FROM (SELECT TB1.ID, TB2.FISH_TYPE, TB2.LENGTH
        FROM FISH_INFO TB1 JOIN (
                            SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
                            FROM FISH_INFO
                            GROUP BY FISH_TYPE) TB2
        ON TB1.FISH_TYPE = TB2.FISH_TYPE
        WHERE TB1.LENGTH = TB2.LENGTH) TB3 JOIN FISH_NAME_INFO TB4
        ON TB3.FISH_TYPE = TB4.FISH_TYPE
ORDER BY TB3.ID ASC;



